# This is a workflow that is manually triggered
name: uses yq image with other tools

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: {}

jobs:
  uses-yq:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: simple yq
      uses: mikefarah/yq@v4.20.1
      with:
        cmd: yq '.on' '.github/workflows/uses-yq.yml'
    - name: with script
      uses: mikefarah/yq@v4.20.1
      with:
        cmd: .github/workflows/uses-yq/try-yq.sh
    - name: with Makefile
      uses: mikefarah/yq@v4.20.1
      with:
        cmd: cd .github/workflows/uses-yq && make try
    - name: with Makefile that calls another Makefile
      uses: mikefarah/yq@v4.20.1
      with:
        cmd: make test-yq
