# This is a workflow that is manually triggered
name: uses yq image with other tools

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: {}

jobs:
  uses-yq:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: v4.20.1
    - name: simple yq
      run: yq '.on' '.github/workflows/uses-yq.yml'
    - name: with script
      run: .github/workflows/uses-yq/try-yq.sh
    - name: with Makefile
      run: cd .github/workflows/uses-yq && make try
    - name: with Makefile that calls another Makefile
      run: make test-yq
